development:
  adapter: postgresql
  encoding: utf8
  database: scenic_app_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: scenic_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: scenic_app
  pool: 5